name: CI
on:
  push:
    branches:
      - master
      - main
  pull_request:


jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: npm ci
      - run: npm run test
      - name: jest test with Coverage
        continue-on-error: true
        working-directory: 'src/ProjectWithJestTests' 
        run: jest --json --outputFile=result.json
      - name: Process jest results with default
        if: always()
        uses: im-open/process-jest-test-results@v2.0.5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          results-file: 'result.json'
